#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker888"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "cd7e1aa7253f49f99f0b0e47e9b4edd6" }
]

[assets]
directory = "./public"
